site_name: 小书
theme:
  name: material
  language: zh
  palette:
    # 1. 日间模式 (用户设备设置为亮色主题时默认启用)
    - media: "(prefers-color-scheme: light)"
      scheme: default         # 使用亮色主题
      primary: teal           # 主色调：青色 
      accent: lime            # 强调色：柠檬绿
      toggle:
        icon: material/brightness-7 # 亮色图标
        name: 切换至深色模式

    # 2. 深色模式 (用户设备设置为深色主题时默认启用)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate           # 使用深色主题
      primary: blue grey      # 主色调：蓝灰色
      accent: amber           # 强调色：琥珀色
      toggle:
        icon: material/brightness-4 # 深色图标
        name: 切换至亮色模式s


site_url: https://csy0101.gitee.io/ptyz/ 
repo_url: https://gitee.com/csy0101/ptyz
remote_name: gitee
branch: gh-pages
site_dir: site





markdown_extensions:
  # 1. 基础语法增强 (解决表格、脚注、删除线、列表问题)
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - admonition

  # 2. PyMdown 扩展 (解决高亮、上下标、键盘按键等问题)
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:             # 开启上标 (^text^)
  - pymdownx.mark:              # 开启高亮 (==text==)
  - pymdownx.tilde:             # 开启下标 (~text~) 和 删除线 (~~text~~)
  - pymdownx.keys               # 键盘按键 (++ctrl+c++)
  - pymdownx.tasklist:          # 任务列表 [x]
      custom_checkbox: true
  - pymdownx.superfences:       # 解决代码块、多层嵌套问题 (关键！)
      preserve_tabs: true
  - pymdownx.details            # 折叠详情页 (??? note)
  - pymdownx.tabbed:            # 选项卡
      alternate_style: true
  - pymdownx.emoji:             # 表情支持 :smile:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:         # 代码高亮增强
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite       # 行内代码高亮

  # 3. 数学公式支持 (解决 LaTeX 问题)
  - pymdownx.arithmatex:
      generic: true

# 4. 必须添加的 JavaScript (让数学公式生效的关键)
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 首页: index.md
  - 测试页: test.md

